apiVersion: apps/v1
kind: Deployment
metadata:
  app:  webDeployment
  labels:
    app:  webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app:  webapp
    spec:
      containers:
      - image:  nginx:latest
        name:  jenkins-pod
        ports:
        - containerPort:  80